### ISSUE TITLE
Basic setup TODO's

### ISSUE THREAD

**Issue by rwjblue** [checkupjs/checkup#2]
- [x] Move linting configuration (deps, eslintrc, etc) into the project root
- [x] Move gitignore into project root
- [x] Add testing for multiple node versions
- [ ] Add testing for windows?
- [x] Change the linting config to be less annoying (closer to a thin layering on top of eslint:recommended + eslint-plugin-node + prettier)

**Comment by scalvert** [comment]
- [ ] Ensure top level README describes the basics of how to setup the project and what it does
- [ ] Ensure release-it configuration is correctly added for each package
- [ ] Ensure labels are correct (based on release-it configuration)

**Comment by scalvert** [comment]
I'm going to close this since we've done most of the basic setup tasks. I'm not convinced we should support windows at this time, but can be convinced otherwise. If so, let's open a separate issue for it.
